context('Actions', () => {
    beforeEach(() => {
      cy.visit('https://staging-siplah.tokoladang.co.id/').viewport(1360, 768)
    })
        
    it('.type() - type into a DOM element ',()=>{
        // login penjual
        cy
        .wait(10000)
        .get('#btn_masuk')
        .click()
        .get('#usernameLoginRef')
        .type('penjual@gmail.com')
        .wait(1000)
        .get('.product-content > .mt15 > .grid-x > .large-12 > :nth-child(3) > .ng-untouched')
        .type('1234')
        .get('#reveal-masuk > .product-content > .mt15 > .grid-x > .large-12 > .button')
        .click()

        // ke pengaturan akun
        cy
        .get('.rounded-img')
        .click()
        .get('[tabindex="0"] > .f-black')
        .click()
        .wait(5000)
        .get('.image-uploader > .button')
        .click()
        .wait(3000)
        .get('.upload-button')
        .click()
        .wait(3000)
        .get('#reveal-photo-profile > .close-button')
        .click()
        .wait(3000)

        // caara menjual produk
        cy
        .get('app-user-seller-menu > :nth-child(3) > :nth-child(1) > a')
        .click()
        .wait(3000)
        .get('.b-radius-5 > .button')
        .click()
        .get('.upload-produk > .grid-x > :nth-child(1)')
        .click()
        .get(':nth-child(1) > .medium-9 > .input-text')
        .click()
        .type('1234567890')
        .wait(3000)
        .get(':nth-child(2) > .medium-9 > .input-text')
        .click()
        .type('Buku Bergambar')
        .wait(3000)
        .get(':nth-child(3) > .medium-9 > .ng-untouched')
        .click()
        .type('untuk di sini , silahkan isihkan deskripsi produk anda dengan minimal 30 karakter/huruf')
        .get(':nth-child(4) > .medium-9 > .input-icon > .input-text')
        .click()
        .get('[aria-label="Buku"] > :nth-child(1)')
        .click()
        .get('.medium-6 > .input-icon > .input-text')
        .click()
        .type('100000000')
        .get('#with_tax')
        .click()
        .get(':nth-child(9) > .medium-9 > .input-icon > .input-text')
        .click()
        .type('10')
        .get(':nth-child(10) > .medium-9 > .input-text')
        .click()
        .type('10')
        .get('#is_new')
        .click()
        .get(':nth-child(13) > .medium-9 > .input-icon > .input-text')
        .click()
        .type('20')
        .get('.pl20 > .input-icon > .input-text')
        .click()
        .clear()
        .type('10')
        .get('.pl15 > .input-icon > .input-text')
        .click()
        .clear()
        .type('10')
        .get('.pr20 > .input-icon > .input-text')
        .click()
        .clear()
        .type('10')
        .get('.float-right.mt20 > .button-blue')
        .click()

        // menuju ke pengaturan toko
        cy
        .get(':nth-child(5) > :nth-child(1) > a')
        .click()
        .get(':nth-child(2) > :nth-child(1) > .small-12 > .button')
        .click()
        // .get(':nth-child(2) > :nth-child(1) > .small-12 > .button')
        // .click()
        

        //logout
        // cy
        // .get('.rounded-img')
        // .click()
        // .wait(10000)
        // .get('#nav-user > .nav-dropdown > :nth-child(2)')
        // .click()
    })

    })